### ISSUE TITLE
Hope 'Twitter Direct' support tweetdeck

### ISSUE THREAD

**Issue by pixiandouban** [chocolateboy/userscripts#13]
On https://tweetdeck.twitter.com/, the link still show t.co, hope Twitter Direct can support tweetdeck.

Thanks for your work.

**Comment by chocolateboy** [comment]
TweetDeck still uses the old link style with the full link in an attribute, so you can use one of the old (new) Twitter addons, [e.g.](https://addons.mozilla.org/firefox/addon/t-co-sanitizer/). Those addons sit on top of Twitter Direct, which fixes the underlying link, so they should be compatible.

**Comment by rubenarslan** [comment]
The link is dead. I found this one https://greasyfork.org/en/scripts/3528-t-co-bypass but it doesn't work.

**Comment by chocolateboy** [comment]
https://greasyfork.org/en/scripts/422633-tweetdeck-direct

**Comment by rubenarslan** [comment]
holy cow, you're quick. thank you so much, works perfectly. is there a way to support your work?

**Comment by chocolateboy** [comment]
Glad it's working for you. I don't have anything set up donation-wise (yet), but thanks!
