### ISSUE TITLE
Twitter Reply Count - no longer works

### ISSUE THREAD

**Issue by darkred** [chocolateboy/userscripts#14]
Greetings

I've noticed that the 'Twitter Reply Count' script no longer works,  i.e. there's no reply count
e.g. for the test URL of the description screenshot: https://twitter.com/TwitterSupport/status/1150813610370748416 
*(open the URL in new tab and click the [timestamp link](https://user-images.githubusercontent.com/723651/104109912-2f4fb380-52db-11eb-8207-36c1097335f3.jpg) if you have login)*

<details>
<summary>Tweet screenshot</summary>

![2021-01-10_003226](https://user-images.githubusercontent.com/723651/104109927-5f975200-52db-11eb-93d2-9f1e162c3792.jpg)
</details>

There's no error in Console.
Tested in fresh profiles of Chrome 87/Firefox 84 with latest TM beta/VM beta, having login to Twitter or not.

Thank you

---

PS. I can't help but mention that there's a "report" of this issue in the [Greasyfork page](https://greasyfork.org/en/scripts/405335-twitter-reply-count/discussions/68552) : 
lazy, one-sentence (plus *Hi* and *Please*!!), and with a `Bad` rating on top, instead of `No rating - just a question/comment`.
The same friggin annoying thing with most of "issue reports" in GF... Combined with hit-and-run clueless "Bad" reviews all over... 
*(I've posted my suggestions about that in Greasyfork Github repo..)*

**Comment by darkred** [comment]
I'd like to note that if you open the above [tweet URL](https://twitter.com/TwitterSupport/status/1150813610370748416) while having login to Twitter,
then by default(=without the script) the reply count appears ok (`825`) but it's just numbers, there's no accompanying text:

<details>
<summary>Screenshot</summary>

![2021-01-11_200140](https://user-images.githubusercontent.com/723651/104220247-e23d2000-5447-11eb-9b7d-8f31eab01aa8.jpg)
</details>

If you click its timestamp link then you get the screenshot of the OP.

**Comment by chocolateboy** [comment]
The text/label is needed and is no longer attached to the tweet.

I have a workaround which is working locally, but it requires a new dependency which isn't ready for release (and which has several other dependencies which I should also release). So you'll have to enjoy the non-drama of not knowing for a while...

Note: I de-listed the script on Greasy Fork months ago when Twitter stopped exposing the stats:

![twitter-reply-count](https://user-images.githubusercontent.com/31533/104222294-009c1f00-543a-11eb-8100-9d40b0078b18.png)

**Comment by darkred** [comment]
Thanks for replying. 

I'm glad you have a workaround.

I wrote this issue guessing that Twitter has probably made it impossible for the script to work again.
And that "Bad" review... You see, I've also written various userscripts, and such "ratings" on GreasyFork never cease to annoy me.
