### ISSUE TITLE
Idea ⸺ Sort the files in the folders by date on GitHub

### ISSUE THREAD

**Issue by Machou** [chocolateboy/userscripts#16]
Hello,

**chocolateboy** can you write a script to sort the files in folders by date for GitHub files in a folder, like :

![Exemple](https://i.ibb.co/f0L4Ht5/Sans-titre-1.jpg)

**Comment by chocolateboy** [comment]
Like [this](https://greasyfork.org/en/scripts/21373-github-sort-content)?

**Comment by Machou** [comment]
Oh, sorry :P
