### ISSUE TITLE
GoogleDWIMages breaks

### ISSUE THREAD

**Issue by re11ding** [chocolateboy/userscripts#17]
Heyo! So, sorry to bother, but I was doing some image searching yesterday with this script installed. Something appears to have changed on google's end as I'm getting this wonderful error in console:

```
Can't find image URL for result (20): TypeError: METADATA[index][1] is null
    nthImageUrl moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:119
    onResult moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:192
    J moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:9
    each moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:9
    init moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:172
    tms_ff3a70de_bd41_4e61_9185_9042d0b6be57 moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:209
    s eval:4
    <anonymous> moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:1
    <anonymous> moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:1
    <anonymous> moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:214
    <anonymous> moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:216
    s eval:4
    t eval:3
    E_u eval:4
    create eval line 2 > Function:74
    create eval line 2 > Function:76
    c eval line 2 > Function:15
    s eval:4
    i eval line 2 > Function:13
    s eval line 2 > Function:13
    v eval:13
    v eval:13
    s eval:4
    t eval:12
    s eval:4
    h eval:12
    h eval:12
    send eval:13
    s eval line 2 > Function:13
    setTimeout eval line 2 > Function:14
    run eval line 2 > Function:16
    runListeners eval line 2 > Function:15
    anonymous eval line 2 > Function:77
    v eval:13
Google DWIMages.user.js:194:17
    onResult moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:194
    J moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:9
    each moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:9
    init moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:172
    tms_ff3a70de_bd41_4e61_9185_9042d0b6be57 moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:209
    s eval:4
    <anonymous> moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:1
    <anonymous> moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:1
    <anonymous> moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:214
    <anonymous> moz-extension://c65a532d-920f-4167-a118-2a2391811c90/userscripts/Google DWIMages.user.js?id=ff3a70de-bd41-4e61-9185-9042d0b6be57:216
    s eval:4
    t eval:3
    E_u eval:4
    create eval line 2 > Function:74
    create eval line 2 > Function:76
    c eval line 2 > Function:15
    s eval:4
    i eval line 2 > Function:13
    s eval line 2 > Function:13
    v eval:13
    v eval:13
    (Async: Async)
    s eval:4
    t eval:12
    s eval:4
    h eval:12
    h eval:12
    send eval:13
    s eval line 2 > Function:13
    setTimeout eval line 2 > Function:14
    run eval line 2 > Function:16
    runListeners eval line 2 > Function:15
    anonymous eval line 2 > Function:77
    v eval:13
```

Hopefully this isn't a matter of google slowly pushing out the update and it's applied to everyone, but essentially due to this error, what happens is that the images it couldn't process are not added to the list. So, the corresponding direct links to images steps back. Meaning after the first failure, the link to the image is for the previous image behind it. This worsens with every error it encounters. You can see it yourself by searching "Lawn Mower" and clicking the one with the granny pushing the mower. That one will be an image that failed to link and everything after links to the wrong image.

**Comment by chocolateboy** [comment]
I can't reproduce this (yes, it's possible they're A/B testing or still rolling this out). In order to investigate, I'll need more details (this applies to any issue report), e.g.:

- Platform
- Browser name/version
- Userscript engine name/version
- Userscript version
- Relevant custom settings
- Other Google addons/userscripts?
- Logged in or not logged in?
- Any errors in the [web/browser console](https://balsamiq.com/support/faqs/browserconsole/)? ✔

My guess is that it's a conflict with another addon ([e.g.](https://github.com/stacybrock/google-tracking-b-gone)), so I'd [rule that out](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles#w_creating-a-profile) first.

**Comment by re11ding** [comment]
Am not sure what you mean by platform, so I am going to assume Google? 
Firefox Browser version 88.0
Tampermonkey 4.13.6136
Google DWIMages 2.3.2
I will need a description of what you mean by custom settings. I did not know the script was configurable.
I have disabled all other scripts and addons not just related to google but to everything except DWIMages. Still gives the error.
Happens both when logged in or not logged in.

So based on this, we know it's not a conflict with another script and/or add-on.

**Comment by chocolateboy** [comment]
> Am not sure what you mean by platform, so I am going to assume Google?

I've changed it to Operating System.

> I will need a description of what you mean by custom settings.

Any relevant settings in Firefox, Tampermonkey, or the script.

> Would you like a copy of the HTML?

Sure, you can email it to me at the address in my profile. Just incognito, though. Please don't send me anything which could expose your account details.

**Comment by re11ding** [comment]
Ah okay. Windows 10 Education Edition version 1709 (incapable of updating further due to functionality issues.)
All Tampermonkey settings are default (Injection mode was originally on instant due to that hacky script I made since it needed it to work, but that's since been reverted to the default before I reported results from earlier.) Script is completely unmodified. It would take far too long to list settings changes on Firefox, so to make it easier, I created a new profile where all settings are default and unchanged, installed the add-on, installed the script, and same issue exists. So it's not a Firefox settings conflict.

I would just list all the Firefox setting changes I made, but there's quite a bit about:configs that are different and it would be very difficult to list them all.

I will email you the incognito HTML in a bit then. I will have everything disabled in order for you to apply the script and see what's wrong.

**Comment by chocolateboy** [comment]
Thanks, got it.

Try [this](https://github.com/chocolateboy/userscripts/raw/google-dwimages-dev/src/google-dwimages.user.js).

**Comment by re11ding** [comment]
Hey nice work! Looks like it's working fine! If I may ask, what changed in the A/B testing to break the script so... selectively? I am still a programmer, just not familiar with javascript. Would love to expand my knowledge a bit, hence why I'm asking.

**Comment by chocolateboy** [comment]
The metadata appears to have switched from (simplified):

#### Mine

```js
[
    { type: "image", index: 0, url: "https://example.com/1.jpg" },
    { type: "relatedSearches", links: [...] }, // no index, but consumes 1
    { type: "image", index: 2, url: "https://example.com/2.jpg" },
]
```

to:

#### Yours

```js
[
    { type: "image", index: 0, url: "https://example.com/1.jpg" },
    { type: "advert", data: [...] }, // no index, and doesn't consume 1
    { type: "image", index: 1, url: "https://example.com/2.jpg" },
]
```

\- which means an array can no longer be used to look up the metadata for an image based on its index. I switched to a Map keyed on the index since the indices may (now) be non-continuous. This is cleaner and probably a bit faster than cloning/duplicating the structure of the original array, so it's an improvement even if they don't roll out this change.

As for why your metadata/results are different than mine: I'm not sure. It looks like there's some advertising-related nodes in your metadata that aren't in mine. I can't tell from the HTML and it might not be visible if you're using an ad-blocker. New advertising widgets, and possibly distinguishing the metadata that populates them from real results, seems like an unsurprising thing for an advertising company to experiment with, particularly when searching for something like "lawn mower".

**Comment by re11ding** [comment]
That's curious. I gave you the complete HTML with all addons and userscripts disabled, so I am unsure as to why this is the case. I wanted the raw to be as clean as possible. If there was some way to make it cleaner, I'm all ears on that one so we may better find the root of the cause. 

Curiously, uBlock does block the elements on both local and online, so if you're using an adblocker yourself, this may be why you don't see it.
