### ISSUE TITLE
Google DWIMages - qutebrowser support

### ISSUE THREAD

**Issue by Riyyi** [chocolateboy/userscripts#18]
Currently only the .tld extension is included, which works on Firefox Violentmonkey, but it doesn't load on qutebrowser (greasemonkey).
```// @include       https://encrypted.google.tld/*tbm=isch*```

It works correctly when changing `.tld` to `.*` or when adding another include with `.com`.

**Comment by chocolateboy** [comment]
[`.tld`](https://wiki.greasespot.net/Magic_TLD) works in all userscript engines, e.g.:

- [FireMonkey](https://github.com/erosman/support/issues/137) (though it doesn't support `@include`)
- Greasemonkey 4
- [Tampermonkey](https://github.com/Tampermonkey/tampermonkey/blob/07f668cd1cabb2939220045839dec4d95d2db0c8/src/helper.js#L20-L21) (although it appears to be broken in Firefox at the moment)
- [USI](https://github.com/usi-firefox/usi/blob/58a2fecdf08ea0ab8c7ca77cd6c6d94dab8277e8/src/lib/parse/convert2RegExp.ts#L28) (which appears to be the only [non-compliant](https://github.com/usi-firefox/usi/blob/58a2fecdf08ea0ab8c7ca77cd6c6d94dab8277e8/src/lib/parse/convert2RegExp.ts#L50) version)
- Violentmonkey

I'm not planning to write out all [190 Google TLDs](https://github.com/chocolateboy/google-direct/blob/v1.0.0/manifest.json#L17-L208), and obviously `.*` is too wide. This is pretty much what `.tld` was made for and there are a large number of userscripts which use it (including other scripts of mine), so I think it would be better to lobby for qutebrowser to support it.

**Comment by chocolateboy** [comment]
https://github.com/qutebrowser/qutebrowser/issues/3238
