### ISSUE TITLE
Twitter Direct and Tweetdeck support

### ISSUE THREAD

**Issue by nagato7** [chocolateboy/userscripts#20]
I've been using Twitter Direct and Tweetdeck Direct(from an [old issue](https://github.com/chocolateboy/userscripts/issues/13)) but Tweetdeck one stopped working and redirects to t.co link even when the userscript is active. I understand Tweetdeck Direct is not actively maintained but I wonder you have plan to fix the issue.

**Comment by chocolateboy** [comment]
Links still worked for me, but not cards. Cards should be fixed in v2.0.1.
