### ISSUE TITLE
IMDb Tomatoes: `error fetching API (420 Connection Error)`

### ISSUE THREAD

**Issue by rakleed** [chocolateboy/userscripts#25]
Console log:
```
[Log] id: – "tt7366338"
[Log] cached error (expires: 17/02/2023, 15:36:42): – "error fetching API (420 Connection Error)"
```
https://github.com/chocolateboy/userscripts/blob/a2935f1e536e42b5cf8b4c92c2cf1cc5f48fbbcc/src/imdb-tomatoes.user.js#L1468

**Comment by chocolateboy** [comment]
![imdb-chernobyl](https://user-images.githubusercontent.com/31533/219373471-00907d03-923c-4cd3-942d-d1fcc8797c19.png)

Transient network error. Either try again tomorrow or [clear the cache](https://wiki.greasespot.net/Greasemonkey_Manual:Monkey_Menu) and try again:

![imdb-tomatoes-menu](https://user-images.githubusercontent.com/31533/219374615-74d8974b-38ab-4682-b0f1-edf3abd1cd7e.png)

**Comment by rakleed** [comment]
I checked and the user script works correctly in Tampermonkey and Violentmonkey. But usually I use AdGaurd for macOS or [Userscripts](https://github.com/quoid/userscripts), and both programs give a similar warning: `GM.registerMenuCommand is not supported`, but this is not critical, and the problem is something else, right?

**Comment by chocolateboy** [comment]
Never heard of AdGuard, but userscript engines which [don't support](https://github.com/quoid/userscripts/issues/232#issuecomment-1060017788) the Greasemonkey 3 API in most cases (including this) — or Greasemonkey 4 API in a few cases — are [not supported](https://github.com/chocolateboy/userscripts#compatibility).

And no, it's not relevant to  resolving a network error on your device.
