### ISSUE TITLE
IMDb Tomatoes Issue on Firefox w/ Violentmonkey

### ISSUE THREAD

**Issue by shadykat01** [chocolateboy/userscripts#26]
On Firefox running the newest version of Violentmonkey, enabling this script causes other scripts to fail to load. Previously, this script didn't cause any issues and was working fine.

Issue Demo: https://m1.afileditch.ch/AuIxhfLPRkFHeuMJRD.gif

Something recent, either an update to Firefox, Violentmonkey or the script itself appears to have broken the ability for this script to operate alongside other scripts.

I'm not facing this issue on Edge browser for some reason.

Steps to Reproduce:

1. Install Firefox Stable or Developer Edition: https://www.mozilla.org/en-US/firefox/all/#product-desktop-developer
2. Install Violentmonkey extension from Addons Store: https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/
3. Install Link 'Em All: https://greasyfork.org/en/scripts/17154-imdb-link-em-all
4. Go to IMDb page for any movie and configure Link Em All script
5. Install IMDb Tomatoes script
6. Restart Firefox
7. Refresh IMDb page

**Comment by chocolateboy** [comment]
I can reproduce this with Violentmonkey 2.13.10. Scripts that run after IMDb Tomatoes are [enabled but greyed out](https://github.com/violentmonkey/violentmonkey/issues/1761) in the menu:

![violentmonkey-inactive-userscripts](https://user-images.githubusercontent.com/31533/219970250-8b0f0ae1-61ad-423f-b640-f20aa7c94efc.png)

I can't reproduce it in the latest beta ([2.13.10.2](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.10.2)), so I suggest upgrading to that or waiting for [2.13.11](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.11) to be approved on AMO:

![violentmonkey-active-userscripts](https://user-images.githubusercontent.com/31533/219970256-c2a69942-0a1b-4d7a-a80f-c480035476dc.png)

**Comment by SleepDaemon** [comment]
> I can reproduce this with Violentmonkey 2.13.10. Scripts that run after IMDb Tomatoes are [enabled but greyed out](https://github.com/violentmonkey/violentmonkey/issues/1761) in the menu:
> 
> ![violentmonkey-inactive-userscripts](https://user-images.githubusercontent.com/31533/219970250-8b0f0ae1-61ad-423f-b640-f20aa7c94efc.png)
> 
> I can't reproduce it in the latest beta ([2.13.10.2](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.10.2)), so I suggest upgrading to that (**create a backup first**) or waiting for [2.13.11](https://github.com/violentmonkey/violentmonkey/releases/tag/v2.13.11) to be approved on AMO:
> 
> ![violentmonkey-active-userscripts](https://user-images.githubusercontent.com/31533/219970256-c2a69942-0a1b-4d7a-a80f-c480035476dc.png)

how long does approval take?
