### ISSUE TITLE
Reddit Color+transparency Adjustment and whole post highlight

### ISSUE THREAD

**Issue by Cooly0** [chocolateboy/userscripts#27]
The bright yellow highlighter is a bit overwhelming.  I was hoping we could be able to adjust color+transparency for the entire post line item, like this extension does & the 2nd one below does for New Comments:
https://chrome.google.com/webstore/detail/reddit-whats-new/acmnikdadpjghhiphlkneneeflhmiidh?hl=en-US&authuser=1

https://chrome.google.com/webstore/detail/reddit-new-comments-highl/ajdilinnnkbmpoegibgacadjlblmpjad?hl=en-US&authuser=1

**Comment by chocolateboy** [comment]
Duplicate of #22.
