### ISSUE TITLE
Search API returns 404s under current query

### ISSUE THREAD

**Issue by curtisgibby** [chocolateboy/userscripts#4]
The current live version of the script returns 404s from the search API. I had to update your API call URL to use the `searchTerm` parameter instead of `title`. Specifically, that meant changing line 312 to 

```javascript
params.searchTerm = searchTerm
```

**Comment by chocolateboy** [comment]
I can't reproduce this. Do you have an example (e.g. IMDb ID) of a title that's found with this query and not found without it?

**Comment by curtisgibby** [comment]
Hmm, perhaps something changed on the Cinesift side. URLs that were previously 404ing for me now return the correct data. My apologies.
