### ISSUE TITLE
DWImages link on image not working anymore

### ISSUE THREAD

**Issue by bohwaz** [chocolateboy/userscripts#8]
It seems that Google is rewriting the href attribute after you set it.

I changed the script to replace the href change with:

```
        $links.eq(0).clone(true).attr('jsname', null).attr('href', meta.ou).insertAfter($links.eq(0));
        $links.eq(0).attr('style', 'display: none');
        $links.eq(1).attr('href', meta.ru) // page

        $links.eq(0).find('img').onModify('src', function (element) {
            element.parent().next().find('img').eq(0).attr('src', element.attr('src'));
        });
```

And it works :)

Edit: forgot the part for the dynamic loading of images when scrolling.

**Comment by chocolateboy** [comment]
Thanks for letting me know!

> Edit: forgot the part for the dynamic loading of images when scrolling.

Yeah, I tried something similar, and ran into the same issue. I've gone with another approach for now. We'' see how long it lasts :-)

**Comment by bohwaz** [comment]
Thanks! I thought it was the jsname attribute that triggered the href overwrite, apparently it's the class name, good to know.
