### ISSUE TITLE
Doesn't work on "search by image" pages

### ISSUE THREAD

**Issue by alexolog** [chocolateboy/userscripts#9]
Example: https://tinyurl.com/wj5hupe

**Comment by chocolateboy** [comment]
Works fine for me. Are you going to the actual image results? (Hint: click "All sizes" or Visually similar images".)

**Comment by alexolog** [comment]
I am clicking on the images on that page (scroll down).  They work fine with Google Direct Links but not for DWIMages.

**Comment by chocolateboy** [comment]
This userscript work on Google Images, not on Google Search:

> Direct links to images and pages on [Google Images](https://www.google.com/imghp).
